upstream next {
   server plywood_nextjs:3000;
}

upstream api {
  server plywood_nestjs:4200;
}

server {
    listen 80;
    server_name plywoodmarket.ru;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


server {
    listen 443 ssl;
    server_name plywoodmarket.ru;
    server_tokens off;

    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    ssl_certificate /etc/letsencrypt/live/plywoodmarket.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plywoodmarket.ru/privkey.pem;

    location / {
        proxy_pass http://next;
    }

    location /api {
        proxy_pass http://api;
    }
}
