version: "3.10"

x-node-version: &node-version node:16.15.0

services:
  db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testik
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgsql-sock:/var/run/postgresql
    networks:
      - web
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: *node-version
    ports:
      - "9000:9000"
    networks:
      - web
    depends_on:
      - db
    volumes:
      - ../backend:/api
      - pgsql-sock:/var/run/postgresql
      - ../backend/assets:/var/lib/images
    working_dir: /api
    command: bash -c "
      yarn install
      && yarn migrate:up
      && yarn start:dev"

  frontend:
    image: *node-version
    ports:
      - "3000:3000"
    networks:
      - web
    depends_on:
      - backend
    volumes:
      - ../frontend:/frontend
    working_dir: /frontend
    command: bash -c "
      yarn install
      && yarn dev"

volumes:
  db:
    driver: local
  pgdata:
  pgsql-sock:

networks:
  web:
