version: "3.3"

services:
  db:
    image: postgres:14.5
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testik
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgsql-sock:/var/run/postgresql
    networks:
      - web

  backend:
    image: node:16.15.0
    container_name: nestjs
    networks:
      - web
    depends_on:
      - db
    volumes:
      - ../backend:/api
      - pgsql-sock:/var/run/postgresql
      - ../backend/assets:/var/lib/images
    working_dir: /api
    command: bash -c "
      yarn install
      && yarn prisma migrate dev
      && yarn prisma db seed
      && yarn start:dev"

  frontend:
    image: node:16.15.0
    container_name: nextjs
    networks:
      - web
    volumes:
      - ../frontend:/frontend
    working_dir: /frontend
    command: bash -c "
      yarn install
      && yarn build
      && yarn start"

  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  pgdata:
  pgsql-sock:

networks:
  web:
